runtime: nodejs18
env: standard
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  # Serve the assets folder
  - url: /assets
    static_dir: dist/assets

  # Serve index.html for all other requests to enable client-side routing
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
