name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Navigate to Front-End/front-end directory
      run: cd Front-End/front-end

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install Dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to Google Cloud
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        deliverables: app.yaml
